=== iva-bashmat/cypher-rules/src/main/resources/static/rule-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://localhost:8080/ruleSchema.json",
  "title": "rule",
  "description": "JSON Schema describing rule",
  "type": "object",
  "properties": {
    "condition": {
      "$ref": "http://localhost:8080/rule-condition-schema.json"
    },
    "compositeConditions": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "condition": {
            "$ref": "http://localhost:8080/rule-condition-schema.json"
          },
          "operator": {
            "type": "string",
            "enum": [
              "AND",
              "OR"
            ]
          }
        },
        "required": [
          "condition",
          "operator"
        ]
      }
    },
    "name": {
      "type": "string"
    },
    "action": {
      "type": "string",
      "enum": [
        "ENABLE",
        "DISABLE"
      ]
    }
  },
  "required": [
    "condition",
    "name",
    "action"
  ]
}

=== iva-bashmat/cypher-rules/src/main/resources/static/rule.json
{
  "name": "A1-to-A2-disable",
  "condition": {
    "propertyName": "route.pol.area",
    "propertyValue": "A1",
    "operator": "EQUALS"
  },
  "compositeConditions": [
    {
      "operator": "AND",
      "condition": {
        "propertyName": "route.pod.area",
        "propertyValue": "A2",
        "operator": "EQUALS"
      }
    }
  ],
  "action": "DISABLE"
}
